#!/bin/bash

# iOS TestFlight Deployment Guide
# ================================
# Este script documenta os passos para fazer build e deploy da App iOS no TestFlight

echo "📱 iOS TestFlight Deployment Checklist"
echo "======================================"
echo ""
echo "ℹ️ PREREQUISITES:"
echo "  1. Xcode instalado (versão 16+)"
echo "  2. Apple Developer Account (pago - $99/ano)"
echo "  3. App Transport Security: SSLPinning desabilitado para API local"
echo ""
echo "📋 PASSOS:"
echo ""
echo "STEP 1: Preparar Projeto no Xcode"
echo "  $ open IOSSimuladorStarter/PsyManager.xcodeproj"
echo "  • Selecionar: Project > PsyManager"
echo "  • Signing & Capabilities:"
echo "    - Team: Seleciona teu Team Apple Developer"
echo "    - Bundle ID: com.franciscomarcondes.psymanager"
echo "    - Ensure provisioning profiles são baixadas"
echo ""
echo "STEP 2: Verificar Build Settings"
echo "  • Build Settings > Code Signing"
echo "    ✓ Code Signing Identity: iOS Developer"
echo "    ✓ Team ID: Teu Team ID"
echo "    ✓ Provisioning Profile: Auto (Managed by Xcode)"
echo ""
echo "STEP 3: Build para Device (Não Simulator)"
echo "  $ xcodebuild -scheme PsyManager \\\\"
echo "      -configuration Release \\\\"
echo "      -destination generic/platform=iOS \\\\"
echo "      -archivePath ./build/PsyManager.xcarchive \\\\"
echo "      archive"
echo ""
echo "  OU via UI:"
echo "  Product > Archive > Choose Device (não Simulator)"
echo ""
echo "STEP 4: Exportar IPA"
echo "  • Abrir Xcode > Window > Organizer"
echo "  • Selecinar seu Archive (PsyManager)"
echo "  • Click 'Distribute App'"
echo "  • Selecionar: TestFlight > Upload"
echo ""
echo "STEP 5: Upload para App Store Connect"
echo "  Via Xcode Organizer:"
echo "  • Validar assinatura e certificados"
echo "  • Click 'Upload...'"
echo "  • Esperar upload completar (~2-5 min)"
echo ""
echo "STEP 6: Configurar no App Store Connect"
echo "  • Abrir: https://appstoreconnect.apple.com"
echo "  • PsyManager > TestFlight > iOS Builds"
echo "  • Selecione o build que fez upload"
echo "  • Configure:"
echo "    ✓ TestFlight Release Notes"
echo "    ✓ Add Internal Testers (desenvolvedores)"
echo "    ✓ Add External Testers (beta testers)"
echo "  • Click 'Submit to TestFlight Review'"
echo ""
echo "STEP 7: Esperar Review (1-2 dias)"
echo "  • Apple revisa o build"
echo "  • Você recebe notificação"
echo "  • Testers recebem link TestFlight"
echo ""
echo "⚠️ COMMON ISSUES:"
echo ""
echo "  Issue: 'Code signing failed'"
echo "  Fix: Verificar Team ID no Signing & Capabilities"
echo ""
echo "  Issue: 'Archive failed: module not found'"
echo "  Fix: Product > Clean Build Folder (Cmd+Shift+K)"
echo ""
echo "  Issue: 'Invalid provisioning profile'"
echo "  Fix: Xcode > Preferences > Accounts > Download Manual Profiles"
echo ""
echo "  Issue: 'Executable is missing required architecture'"
echo "  Fix: Build Settings > Architectures = ARM64 (não x86_64)"
echo ""
echo "📲 TESTING NO DEVICE:"
echo "  • Connect iPhone via USB"
echo "  • Produto > Destination > [seu iPhone]"
echo "  • Cmd+R para build + run"
echo "  • Trust certificado de desenvolvimento no iPhone"
echo ""
echo "✅ DEPLOYMENT COMPLETE"
echo ""
echo "Links úteis:"
echo "  • App Store Connect: https://appstoreconnect.apple.com"
echo "  • TestFlight Documentation: https://developer.apple.com/testflight/"
echo "  • Xcode Documentation: https://developer.apple.com/documentation/xcode"
